version: '3'

services:
  web:
    image: nginx:latest
    ports:
     - "80:80"
    volumes:
     - ./nginx/nginx.conf:/ect/nginx/conf.d/default.conf
     - ./src:/usr/share/nginx/html
     - ./latihan:/usr/share/nginx/html/latihan